### ISSUE TITLE
Google Image ?

### ISSUE THREAD

**Issue by NicotherZ** [JadeVane/stylus-for-google-result#1]
Hi,
Thanks for your work, it's works perfect, just wanted to know if you can do the same for google images ?
Not for all the page, just search bar and option bar.
Thanks!

**Comment by JadeVane** [comment]
Just made an adaptation for it, try the latest version.

**Comment by NicotherZ** [comment]
Almost perfect : https://i.imgur.com/nraST6H.jpeg ^^
Thank you very much for your work !

**Comment by JadeVane** [comment]
I just overlooked that, and it's fixed now.

**Comment by NicotherZ** [comment]
Perfect !! Thank you very much for your work !

**Comment by JadeVane** [comment]
My pleasure.
